# create a user object (find the user)
import sqlite3
from db import db

class UserModel(db.Model):  # save this object in SQLAlchemy (database)
    __tablename__ = 'users'

    # define 3 columns to be stored in DB
    id = db.Column(db.Integer, primary_key=True) # define column ID as primary key (unique index)
    username = db.Column(db.String(80))
    password = db.Column(db.String(80))
    
    def __init__(self, username, password): # ID will be automatically generated by SQLAlchemy
        self.username = username
        self.password = password

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    @classmethod  # we use the Class + "self" is not used in this method
    def find_by_username(cls, username):
        return cls.query.filter_by(username=username).first() # return UserModel object

    
    @classmethod  # we use the Class + "self" is not used in this method
    def find_by_id(cls, _id):
        return cls.query.filter_by(id=_id).first()